env:
  es6: true
  node: true
extends:
  - airbnb-base
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
rules: { "import/extensions": "never", "prefer-const": 0 }
settings:
  import/resolver:
    node:
      extensions: [".js", ".jsx", ".ts", ".tsx", ".d.ts"]
